config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root  'photos#index'
  post   '/like/:photo_id', to: 'likes#create' , as: 'like'
  delete '/like/:photo_id', to: 'likes#destroy', as: 'unlike'

  resources :photos do
    resources :comments, only: [:create]
    collection do
      get 'post'
    end
  end
  resources :albums
  resources :users, only: [:show]
end

app/models/album.rb
class Album < ApplicationRecord
  # has_many :photos, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :photo
  belongs_to :user 
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :photo, counter_cache: :likes_count
  belongs_to :user
end

app/models/photo.rb
class Photo < ApplicationRecord

  # mount_uploader :image, ImageUploader, presence: true
  has_one_attached :image
  with_options presence: true do
  validates :text  
  validates :name
  validates :image
  end

  # belongs_to :album
  belongs_to :user, optional: true
  has_many :comments,foreign_key: :photo_id, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname
    validates :email
    validates :password
    validates :password_confirmation
  end

  has_many :photos
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :like_stories, through: :likes, source: :photo
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
  end

  def new
    @album = Album.new
  end

  def show
  end

  def edit
  end

  def destroy
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(text: comment_params[:text], photo_id: comment_params[:photo_id], user_id: current_user.id)
    respond_to do |format|
      format.html { redirect_to photo_path(params[:photo_id]) }
      format.json
    end
  end

  private
  def comment_params
    params.permit(:text, :photo_id)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables

  def create
    like = current_user.likes.create(photo_id: @photo.id)
    like.save
  end

  def destroy
    like = current_user.likes.find_by(photo_id: @photo.id)
    like.destroy
  end

  private

  def set_variables
    @photo = Photo.find(params[:photo_id])
    @id_name = "#like-link-#{@photo.id}"
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  before_action :move_to_index, except: [:index, :show]

  def index
    @photo = Photo.includes(:user).page(params[:page]).per(8).order("created_at DESC")
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.create(photo_params)
    if @photo.save
    else
      render :new
    end
  end

  def show
    @photo = Photo.find(params[:id])
    @comments = @photo.comments.includes(:user)
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.user_id == current_user.id
      @photo.update(photo_params)
    end
  end

  def destroy
    photo = Photo.find(params[:id])
    photo.destroy if photo.user_id == current_user.id
  end


  private

  def photo_params
    params.require(:photo).permit(:name, :text, :image).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @nickname = current_user.nickname
    @photo = current_user.photos.page(params[:page]).per(5).order("created_at DESC")
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/index.html.haml
= render 'layouts/header'
.albums
  .albums__area
    .albums__left-box
      .albums__left-box__info
      .albums__left-box__image
      .albums__left-box__name
      .albums__left-box__text
    .albums__right-box
      .albums__right-box__info
      .albums__right-box__image
      .albums__right-box__name
      .albums__right-box__text
= render 'layouts/footer'

app/views/layouts/_footer.html.haml
.footer
  .footer__logo
    © 2019 naomotchi Inc.

app/views/layouts/_header.html.haml
.header
  .header__top
    .header__top__logo
      .header__top__logoul
        = link_to root_path, id: "header_title" do
          Pet-Phots
        .header__top__logoli
          submission site
    .header__top__user
      .header__top__user__info
        - if user_signed_in?
          = "ようこそ！#{current_user.nickname}さん"
        - else
          ようこそゲストさん
      - if user_signed_in?
        .header__top__user__mypage
          = link_to "マイページ", "/users/#{current_user.id}", class: "user_sign"
        .header__top__user__post
          = link_to "投稿する", new_photo_path, class: "user_sign"
        .header__top__user__logout
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "user_sign"
      - else
        .header__top__user__login
          = link_to "ログイン", new_user_session_path, class: "user_sign"
        .header__top__user__signin
          = link_to "新規登録", new_user_registration_path, class: "user_sign"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Petphotos
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      = yield

app/views/likes/_like.html.haml
.iine
  - if current_user.likes.find_by(photo_id: photo.id)
    = link_to unlike_path(photo.id), method: :delete, remote: true, class: "iine__button", id:"like-link-#{photo.id}" do
      %i.fa.fa-heart.heart-like
      %p.info いいね!
      %P.up
        = "#{photo.likes.count}"
  - else
    = link_to like_path(photo.id), method: :post, remote: true, class: "iine__button", id:"like-link-#{photo.id}" do
      %i.fa.fa-heart.heart-like
      %p.info いいね!
      %P.down
        = "#{photo.likes.count}"

app/views/likes/create.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", photo: @photo  )) %>')

app/views/likes/destroy.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", photo: @photo  )) %>');

app/views/photos/_album_contents.html.haml
.main-contents__album
  .album__box
    = link_to albums_path, style: "text-decoration: none;" do
      = image_tag src="https://pro.foto.ne.jp/free/img/images_thumb/cat0095-066.jpg", id: "pickup-image"
      .album__photo
      .album__body
        %h3.album-name 
          アルバム名
  .album__box
    = link_to "/", style: "text-decoration: none;" do
      = image_tag src="https://pro.foto.ne.jp/free/img/images_thumb/cat0095-066.jpg", id: "pickup-image"
      .album__photo
      .album__body
        %h3.album-name 
          アルバム名
  .album__box
    = link_to "/", style: "text-decoration: none;" do
      = image_tag src="https://pro.foto.ne.jp/free/img/images_thumb/cat0095-066.jpg", id: "pickup-image"
      .album__photo
      .album__body
        %h3.album-name 
          アルバム名
  .album__box
    = link_to "/", style: "text-decoration: none;" do
      = image_tag src="https://pro.foto.ne.jp/free/img/images_thumb/cat0095-066.jpg", id: "pickup-image"
      .album__photo
      .album__body
        %h3.album-name 
          アルバム名
  .album__box
    = link_to "/", style: "text-decoration: none;" do
      = image_tag src="https://pro.foto.ne.jp/free/img/images_thumb/cat0095-066.jpg", id: "pickup-image"
      .album__photo
      .album__body
        %h3.album-name 
          アルバム名
  .album__box
    = link_to "/", style: "text-decoration: none;" do
      = image_tag src="https://pro.foto.ne.jp/free/img/images_thumb/cat0095-066.jpg", id: "pickup-image"
      .album__photo
      .album__body
        %h3.album-name 
          アルバム名

app/views/photos/_comments.html.haml
.comments
  - if current_user
    .comments__form
      相手のことを考え丁寧なコメントを心がけましょう。
      %br/
      不快な言葉遣いなどは利用制限や退会処分となることがあります。
      = form_with url: photo_comments_path(@photo.id), method: :post, local: true ,id: "new_comment" do |f|
        .photo-form__box__text
          = f.text_area :text, id: "input-text", class: "textbox"
        .photo-form__box__btn
          %label(for="form-btn")
            コメントする
            = f.submit "コメントする", id: "form-btn", class: "submit-btn", style: "display:none;"
= render 'messages'

app/views/photos/_messages.html.haml
.messages
  .messages__info
    コメント一覧
  .messages__area
    - if @comments
      - @comments.each do |c|
        -if c.user_id == current_user.id
          .messages__box
            .messages__box__name
              = c.user.nickname
            .messages__box__text
              = c.text
.background--gray

app/views/photos/_photos.html.haml
= render 'likes/like', photo: @photo

app/views/photos/_photos_infomartion.html.haml
.main-contents
  .main-contents__image
    = link_to '/' do
      = image_tag src="https://rank1-media.com/file/parts/I0003875/73e68ce9a3c2dc9827cdf6e7db68282c.jpg", id: "main-image"
  .main-contents__info
    可愛いペットの写真を投稿しましょう
  = render 'pickup_contents'
  -# .main-contents__info
  -#   みんなのアルバム
  -# = render 'album_contents'
  .main-contents__info
    全ての動物に救いの手を
  .main-contents__protection
    .main-contents__protection__image
      = image_tag src="https://pro.foto.ne.jp/free/img/images_big/m030633.jpg"
  .main-contents__bottom
    - if user_signed_in?
      = link_to "大切な家族との想い出を記録する(投稿する)", new_photo_path, id: "info-link"
    - else
      = link_to "大切な家族との想い出を記録する(無料登録はこちら)", new_user_registration_path, id: "info-link"

app/views/photos/_pickup_contents.html.haml
.main-contents__pickup
  .pickup__title
    新着ペット一覧
  - @photo.each do |photo|
    .pickup__box
      = link_to photo_path(photo), style: "text-decoration: none;" do
        .pickup__photo
          = image_tag url_for(photo.image), id: "pickup-image"
        .pickup__body
          %h3.photos-name 
            = photo.name
          .photos-box
            .photos-text
              =photo.text
            .photos-like
              %i.fa.fa-heart
              = "#{photo.likes.count}"

app/views/photos/create.html.haml
= render 'layouts/header'
.posts
  .posts__area
    .posts__box
      .posts__box__info
        投稿が完了しました
      .posts__box__btn
        = link_to "トップページにもどる", root_path, id: "post_btn"
= render 'layouts/footer'

app/views/photos/destroy.html.haml
= render 'layouts/header'
.posts
  .posts__area
    .posts__box
      .posts__box__info
        削除が完了しました
      .posts__box__btn
        = link_to "トップページにもどる", root_path, id: "post_btn"
= render 'layouts/footer'

app/views/photos/edit.html.haml
= render 'layouts/header'
.photo-form
  .photo-form__area
    .photo-form__box
      編集フォーム
      .field.image
        = form_with(model: @photo, local: true) do |form|
          .photo-form__box__info
            画像を選んでください
          %label(for="file")
            #img_field{onclick: "$('#file').click()"}
              %i.fa.fa-camera
              = form.file_field :images, multiple: true, class: "image", id: "file", style: "display:none;"
          .photo-form__box__info
            お名前を入力してください
          .photo-form__box__name
            = form.text_field :name, id: "form-name"
          .photo-form__box__info
            コメントを入力してください
          .photo-form__box__text
            = form.text_area :text, id: "form-text"
          .photo-form__box__btn
            %label(for="form-btn")
              編集する
              = form.submit "編集する", id: "form-btn", style: "display:none;"
= render 'layouts/footer'

app/views/photos/index.html.haml
.container
  = render 'layouts/header'
  = render 'photos_infomartion'
  = render 'layouts/footer'

app/views/photos/new.html.haml
= render 'layouts/header'
= render 'post_form'
= render 'layouts/footer'

app/views/photos/post.html.haml
= render 'layouts/header'
.posts
  .posts__area
    .posts__box
      .posts__box__info
        投稿が完了しました
      .posts__box__btn
        = link_to "トップページにもどる", root_path, id: "post_btn"
= render 'layouts/footer'

app/views/photos/show.html.haml
= render 'layouts/header'
.details
  .details__area
    .details__box
      .details__box__info
        = "#{@photo.user.nickname}さんの投稿"
      .details__box__photos
        .details__box__photo
          = image_tag url_for(@photo.image), id: "details-image"
        .details__box__body
          .details-name
            = @photo.name
          .details-text
            = @photo.text
        - if user_signed_in? && current_user.id == @photo.user_id
          .details__box__edit
            = link_to '編集', edit_photo_path(@photo), method: :get, id: "defalut-link"
          .details__box__delete
            = link_to '削除', photo_path(@photo.id), method: :delete , id: "defalut-link"
        - if user_signed_in?
          - unless current_user.id == @photo.user_id
            = render partial: 'photos/photos', member: @photo, as: :photo
        .details__box__btn
          = link_to "トップページにもどる", root_path, id: "details-btn", class: "details__box__btn"
    = render 'comments'
= render 'layouts/footer'

app/views/photos/update.html.haml
= render 'layouts/header'
.posts
  .posts__area
    .posts__box
      .posts__box__info
        更新が完了しました
      .posts__box__btn
        = link_to "トップページにもどる", root_path, id: "post_btn"
= render 'layouts/footer'

app/views/users/_mypage.html.haml
.mypage
  .mypage__name
    = "#{current_user.nickname}さんのマイページ"
  .mypage__area
    - @photo.each do |photo|
      .mypage__box
        = link_to "/", style: "text-decoration: none;" do
          .mypage__photo
            = image_tag url_for(photo.image), id: "mypage-image"
          .mypage__body
            .mypage-name
              = photo.name
            .mypage-box
              .mypage-text
                = photo.text
            - if user_signed_in? && current_user.id == photo.user_id
              .mypage-edit
                = link_to '編集', edit_photo_path(photo), method: :get, id: "defalut-link"
              .mypage-delete
                = link_to '削除', "/photos/#{photo.id}", method: :delete, id: "defalut-link"

app/views/users/show.html.haml
= render 'layouts/header'
.posts
  .posts__area
    = render 'mypage'
  .paginate-defalut
    = paginate(@photo)
= render 'layouts/footer'